[project]
name = "sofie"
version = "0.1.0"
description = "Sofie Aviation Assistant"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = [] 